# docker-compose.yml
version: "2.0"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./Tables.sql:/docker-entrypoint-initdb.d/Tables.sql
      - app-data:/tmp:z

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: go.env
    depends_on:
      - database
    ports:
      - "2020:2020"
    volumes:
      - app-data:/tmp:z

volumes:
  data:
  app-data:
